# top level stuff you probably don't need to touch
highlighter: pygments
markdown: kramdown
permalink: /blog/:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://www.brendangriffen.com
baseurl: /
title: Brendan Griffen
author: Brendan Griffen
description: A human exploring the very large and the very small.
avatar: profile.jpg
email: brendan.f.griffen@gmail.com
github: bgriffen
twitter: brendangriffen
linkedin: brendangriffen
feed: brendangriffen
stackoverflow: users/1495869/griff   #e.g: users/2735833/proton1h1
medium: brendangriffen
#Comment out if you don't want disqus 
disqus: brendangriffen
google_analytics: UA-2011187-3


# needed for travis-ci build
exclude: [vendor]
